// Roslyn Quoter: https://roslynquoter.azurewebsites.net/

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

string[] classNames = ["Movie", "Director", "Actor"];
foreach (var className in classNames)
{
    var code = RecordDeclaration(Token(SyntaxKind.RecordKeyword), className)
        .AddModifiers(
            Token(SyntaxKind.PublicKeyword).WithLeadingTrivia(Comment("// <auto-generated>")),
            Token(SyntaxKind.PartialKeyword))
        .WithSemicolonToken(Token(SyntaxKind.SemicolonToken))
        .NormalizeWhitespace();

    var generateSourceFilePath = Path.GetFullPath($"../../../{className}.cs");
    File.WriteAllText(generateSourceFilePath, code.ToFullString());
}
