// Roslyn Quoter: https://roslynquoter.azurewebsites.net/

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

string[] classNames = ["Movie", "Director", "Actor"];

foreach (var className in classNames)
{
    var code = RecordDeclaration(Token(SyntaxKind.RecordKeyword), className)
        .WithModifiers(
            TokenList(
                Token(
                    TriviaList(Comment("// <auto-generated/>")),
                    SyntaxKind.PublicKeyword,
                    TriviaList())))
        .WithSemicolonToken(Token(SyntaxKind.SemicolonToken))
        .NormalizeWhitespace();
   
    var generateSourceFilePath = Path.GetFullPath($"../../../{className}.cs");
    File.WriteAllText(generateSourceFilePath, code.ToFullString());
}
