// Roslyn Quoter: https://roslynquoter.azurewebsites.net/

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

string[] recordNames = ["Movie", "Director", "Actor"];

foreach (var recordName in recordNames)
{
    var recordFilePath = Path.GetFullPath($"../../../{recordName}.cs");

    var record = RecordDeclaration(Token(SyntaxKind.RecordKeyword), recordName)
        .AddModifiers(
            Token(SyntaxKind.PublicKeyword).WithLeadingTrivia(Comment("// <auto-generated>")),
            Token(SyntaxKind.PartialKeyword))
        .WithSemicolonToken(Token(SyntaxKind.SemicolonToken))
        .NormalizeWhitespace();

    File.WriteAllText(recordFilePath, record.ToFullString());
}
